### ISSUE TITLE
NOAA contact

### ISSUE THREAD

**Issue by eugeneburger** [NOAAGov/NOAA-Affiliated-Projects#10]
Hi, 

There are some questions from several of us on linking (NOAA) projects here and NOAA GH policy. Can the repo owner please contact me?

Thanks

**Comment by eugeneburger** [comment]
Resolved

**Comment by JordanMakesMaps** [comment]
Hi, I have the same question as @eugeneburger. Can the Repo owner please contact me? Thanks!
