### ISSUE TITLE
NOAA-NCEI project initialization

### ISSUE THREAD

**Issue by monocongo** [NOAAGov/NOAA-Affiliated-Projects#3]
I would like to get the ball rolling for the establishment of a NOAA-NCEI project to contain open source git repositories for code developed at NCEI. Is there a process for this? Who has the authority to approve, etc.? Thanks in advance for any guidance.

**Comment by shanecglass** [comment]
Sorry for the delayed response! 

I'm happy to help you through the process. I will follow up with you via email. 

SCG

**Comment by eugeneburger** [comment]
Hi,

Have you received the information you were looking for? If not, please let me know and I can help guide you in the right direction.

Best
  Eugene Burger

**Comment by baldwinrich** [comment]
Please close issue.  James is no longer associated with NCEI.

**Comment by eugeneburger** [comment]
Resolved. Apologies for the delay.
